networks:
  dev_net:
    driver: bridge


services:
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sve
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: inventory

    # env_file:
    #   - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./scripts/dev-db-setup.sh:/docker-entrypoint-initdb.d/dev-db-setup.sh
    networks:
      - dev_net

  #     - 5434:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev_net

name: fastapi-development
